from __future__ import annotations

import os
import sqlite3
from contextlib import closing
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

DEFAULT_DB_PATH = (
    Path(os.environ.get("MASTER_STORAGE", str(Path.home() / ".termux_master"))) / "state.db"
)


def get_connection(db_path: Path | str = DEFAULT_DB_PATH) -> sqlite3.Connection:
    """Create a new SQLite connection.

    Caller must ensure the connection is closed (e.g., via contextlib.closing).
    """
    conn = sqlite3.connect(str(db_path), timeout=10.0)
    conn.row_factory = sqlite3.Row
    return conn


def init_db(db_path: Path | str = DEFAULT_DB_PATH) -> None:
    """Initialize the SQLite database schema if it does not exist."""
    path = Path(db_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with closing(get_connection(path)) as conn:
        with conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS runs (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    dag TEXT NOT NULL,
                    status TEXT NOT NULL,
                    started_at TEXT NOT NULL,
                    ended_at TEXT,
                    error TEXT
                );
                """
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_runs_dag_started ON runs(dag, started_at DESC);"
            )


def record_start(dag: str, db_path: Path | str = DEFAULT_DB_PATH) -> int:
    """Record the start of a DAG run and return its unique run ID."""
    started_at = datetime.now(timezone.utc).isoformat()
    with closing(get_connection(db_path)) as conn:
        with conn:
            cursor = conn.execute(
                "INSERT INTO runs (dag, status, started_at) VALUES (?, 'running', ?);",
                (dag, started_at),
            )
            return cursor.lastrowid  # type: ignore[no-any-return]


def record_finish(
    run_id: int,
    status: str,
    error: Optional[str] = None,
    db_path: Path | str = DEFAULT_DB_PATH,
) -> bool:
    """Record the completion or failure of a DAG run.

    Contract: assumes run_id was generated by record_start.
    Returns True if a record was updated, False if run_id was not found.
    """
    ended_at = datetime.now(timezone.utc).isoformat()
    with closing(get_connection(db_path)) as conn:
        with conn:
            cursor = conn.execute(
                "UPDATE runs SET status = ?, ended_at = ?, error = ? WHERE id = ?;",
                (status, ended_at, error, run_id),
            )
            return cursor.rowcount > 0


def get_last_run(dag: str, db_path: Path | str = DEFAULT_DB_PATH) -> Optional[Dict[str, Any]]:
    """Retrieve the most recent run details for a given DAG."""
    with closing(get_connection(db_path)) as conn:
        cursor = conn.execute(
            """
            SELECT id, dag, status, started_at, ended_at, error
            FROM runs WHERE dag = ? ORDER BY id DESC LIMIT 1;
            """,
            (dag,),
        )
        row = cursor.fetchone()
        return dict(row) if row else None


def list_runs(
    limit: int = 50, dag: Optional[str] = None, db_path: Path | str = DEFAULT_DB_PATH
) -> List[Dict[str, Any]]:
    """List recent runs up to the specified limit, optionally filtered by dag."""
    with closing(get_connection(db_path)) as conn:
        if dag:
            cursor = conn.execute(
                "SELECT id, dag, status, started_at, ended_at, error FROM runs WHERE dag = ? ORDER BY id DESC LIMIT ?;",
                (dag, limit),
            )
        else:
            cursor = conn.execute(
                "SELECT id, dag, status, started_at, ended_at, error FROM runs ORDER BY id DESC LIMIT ?;",
                (limit,),
            )
        return [dict(row) for row in cursor.fetchall()]


# ---------------------------------------------------------------------------
# CLI: lets master.sh (POSIX sh) call this module without a Python wrapper.
#   python3 state.py record-start <dag>              -> prints run_id
#   python3 state.py record-finish <run_id> <status> [error]
# Exits non-zero on misuse so callers under `set -e` fail loudly.
# ---------------------------------------------------------------------------
def _cli() -> int:
    import sys

    init_db()
    args = sys.argv[1:]
    if not args:
        print("usage: state.py record-start <dag> | record-finish <run_id> <status> [error]", file=sys.stderr)
        return 2

    cmd = args[0]
    if cmd == "record-start":
        if len(args) != 2:
            print("usage: state.py record-start <dag>", file=sys.stderr)
            return 2
        run_id = record_start(args[1])
        print(run_id)
        return 0

    if cmd == "record-finish":
        if len(args) not in (3, 4):
            print("usage: state.py record-finish <run_id> <status> [error]", file=sys.stderr)
            return 2
        try:
            run_id = int(args[1])
        except ValueError:
            print(f"run_id must be an integer, got: {args[1]}", file=sys.stderr)
            return 2
        status = args[2]
        error = args[3] if len(args) == 4 else None
        updated = record_finish(run_id, status, error)
        if not updated:
            print(f"warning: no run found with id={run_id}", file=sys.stderr)
            return 1
        return 0

    print(f"unknown subcommand: {cmd}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    import sys
    sys.exit(_cli())
